# Generated by Django 4.1.4 on 2022-12-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_shift_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='end_time',
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name='shift',
            name='start_time',
            field=models.TimeField(default=None),
        ),
    ]
